[package]
name = "deployer"
version = "1.0.0"
edition = "2024"
authors = ["Interchouette <contact@interchouette.net>"]

[dependencies]
wasm-bindgen = "0.2.126"
wasm-bindgen-futures = "0.4.76"
casper-types = { version = "7.0.0", default-features = false }
js-sys = "0.3.103"
base64 = { version = "0.23.0", default-features = false, features = ["alloc"] }
getrandom = { version = "0.4.3", features = ["wasm_js"] }

[lib]
crate-type = ["cdylib"]
