export enum api_interface {
  Users = 'users',
  Peers = 'peers',
  PurseURef = 'purseURef',
  Balance = 'balance',
  Status = 'status',
  State = 'state',
  Dictionary = 'dict',
  Deploy_info = 'deploy_info',
  Put_Deploy = 'put_deploy',
  Transaction_info = 'transaction_info',
  Put_Transaction = 'put_transaction',
  Deployer = 'deployer',
  BalanceOfByPublicKey = 'balanceOfByPublicKey',
  GetStateRootHash = 'getStateRootHash',
}
